app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Registrarte
Route::get('/public/registrar', [
    'uses'  => 'PersonaController@registrar',
    'as'    => 'public.registrar'
]);
Route::post('/public/store', [
    'uses'  => 'PersonaController@store',
    'as'    => 'public.store'
]);

Route::group(['middleware' => 'auth'], function () {
	
    //Modulos del uduario tipo:estudiante
        Route::get('estudiante/', [
        'uses'  => 'PersonaController@inicio',
        'as'    => 'estudiante.inicio'
        ]);

        Route::get('/estudiante/modulos/1/clase1', [
        'uses'  => 'ClaseController@clase1',
        'as'    => 'estudiante.modulos.1.clase1'
        ]);
        Route::get('/estudiante/modulos/1/practica1', [
        'uses'  => 'EvaluacionController@practica1',
        'as'    => 'estudiante.modulos.1.practica1'
        ]);


    Route::resource('clases', 'ClaseController');

    Route::resource('personas', 'PersonaController');

    Route::resource('modulos', 'ModuloController');

    Route::resource('videos', 'VideoController');

    Route::resource('imagens', 'ImagenController');

    Route::resource('opcions', 'OpcionController');

    Route::resource('seccions', 'SeccionController');

    Route::resource('temas', 'TemaController');

    Route::resource('posts', 'PostController');

    Route::resource('comentarios', 'ComentarioController');

    Route::resource('evaluacions', 'EvaluacionController');
});

//rutas temporales del foro
Route::controller('forum', 'foroController', [
    'getIndex'      => 'forum.home',
    'getIndexTema'  => 'forum.tema',  
]);

Route::get('/', [
    'uses'  => 'Auth\AuthController@getLogin',
    'as'    => 'auth.login'
]);

Route::post('/', [
    'uses'  => 'Auth\AuthController@postLogin',
    'as'    => 'auth.login'
]);

Route::get('/logout', [
    'uses'  => 'Auth\AuthController@getLogout',
    'as'    => 'auth.logout'
]);

resources/views/clases/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">Create New Clase</h1>
        </div>
    </div>

    @include('core-templates::common.errors')

    <div class="row">
        {!! Form::open(['route' => 'clases.store']) !!}

            @include('clases.fields')

        {!! Form::close() !!}
    </div>
@endsection

resources/views/clases/edit.blade.php
@extends('layouts.app')

@section('content')
        <div class="row">
            <div class="col-sm-12">
                <h1 class="pull-left">Edit Clase</h1>
            </div>
        </div>

        @include('core-templates::common.errors')

        <div class="row">
            {!! Form::model($clase, ['route' => ['clases.update', $clase->id], 'method' => 'patch']) !!}

            @include('clases.fields')

            {!! Form::close() !!}
        </div>
@endsection

resources/views/clases/fields.blade.php
<!-- Titulo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('titulo', 'Titulo:') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<!-- Contenido Field -->
<div class="form-group col-sm-6">
    {!! Form::label('contenido', 'Contenido:') !!}
    {!! Form::text('contenido', null, ['class' => 'form-control']) !!}
</div>

<!-- Modulo Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('modulo_id', 'Modulo Id:') !!}
    {!! Form::number('modulo_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('clases.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/clases/index.blade.php
@extends('layouts.app')

@section('content')
        <h1 class="pull-left">Clases</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('clases.create') !!}">Add New</a>

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        @include('clases.table')
        
@endsection

resources/views/clases/show.blade.php
@extends('layouts.app')

@section('content')
    @include('clases.show_fields')

    <div class="form-group">
           <a href="{!! route('clases.index') !!}" class="btn btn-default">Back</a>
    </div>
@endsection

resources/views/clases/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $clase->id !!}</p>
</div>

<!-- Titulo Field -->
<div class="form-group">
    {!! Form::label('titulo', 'Titulo:') !!}
    <p>{!! $clase->titulo !!}</p>
</div>

<!-- Contenido Field -->
<div class="form-group">
    {!! Form::label('contenido', 'Contenido:') !!}
    <p>{!! $clase->contenido !!}</p>
</div>

<!-- Modulo Id Field -->
<div class="form-group">
    {!! Form::label('modulo_id', 'Modulo Id:') !!}
    <p>{!! $clase->modulo_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $clase->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $clase->updated_at !!}</p>
</div>

resources/views/clases/table.blade.php
<table class="table table-responsive" id="clases-table">
    <thead>
        <th>Titulo</th>
        <th>Contenido</th>
        <th>Modulo Id</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($clases as $clase)
        <tr>
            <td>{!! $clase->titulo !!}</td>
            <td>{!! $clase->contenido !!}</td>
            <td>{!! $clase->modulo_id !!}</td>
            <td>
                {!! Form::open(['route' => ['clases.destroy', $clase->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('clases.show', [$clase->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('clases.edit', [$clase->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>